# Generated by Django 5.0.1 on 2025-11-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_version', models.CharField(max_length=255)),
                ('webmin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Máquina Virtual',
                'verbose_name_plural': 'Máquinas Virtuales',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='VMStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_usage', models.FloatField()),
                ('ram_total', models.FloatField()),
                ('ram_used', models.FloatField()),
                ('ram_percent', models.FloatField()),
                ('disk_total', models.FloatField()),
                ('disk_used', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('update_count', models.IntegerField(default=-1)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='monitor.virtualmachine')),
            ],
            options={
                'verbose_name': 'Estado de VM',
                'verbose_name_plural': 'Estados de VMs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountpoint', models.CharField(max_length=255)),
                ('total_mb', models.FloatField()),
                ('used_mb', models.FloatField()),
                ('used_percent', models.FloatField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='monitor.vmstatus')),
            ],
            options={
                'verbose_name': 'Partición',
                'verbose_name_plural': 'Particiones',
            },
        ),
        migrations.AddIndex(
            model_name='vmstatus',
            index=models.Index(fields=['vm', '-timestamp'], name='monitor_vms_vm_id_1eb366_idx'),
        ),
    ]
